Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
    config.vm.synced_folder ".", "/var/www/html"  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"  
  end
  
config.vm.provision "shell", inline: <<-SHELL
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt install -y apache2
SHELL

end